#!/usr/bin/env bash
shopt -s nullglob
shopt -s extglob
shopt -s nocasematch


unset CDPATH

MATH_ROOT_DIR="${TMPDIR}/matrix"

if [[ ! -d $MATH_ROOT_DIR ]]; then
    mkdir "${MATH_ROOT_DIR}"
fi

__="${MATH_ROOT_DIR}"


errCheck.Matrix() {
    if [[ "${#@}" -eq 0 ]]; then
        printf 'Argument cannot be null.\n'
        return 1
    fi
    :
    if [[ ! "${1}"  =~ ^[a-zA-Z]+$ ]]; then
        printf 'Names may only include letters.\n'
        return 1
    fi
    :
    IFS=,
    for x in ${@:2}
    do
        if [[  ! $x =~ ^[0-9]+$ ]]; then
            printf 'All elements must be numeric!\n'
            return 1
        fi

    done

    return 0
}

xstCheck.Matrix() {
    [[ ! -f "${__}/matrix.$1" ]] && \
        printf '%s\n' "No such matrix." && return 1
}

unset X
unset Y

declare -A X
declare -A Y


function Matrix() {
    # Good
 #   errCheck.Matrix "${@}" || return 1
 #   xstCheck.Matrix "${1}" && return 1

    declare -r name="${1}"
    shift

    IFS=" "
    out=""
    for oo in "${@}"
    do
        out+="${oo}\\n"
    done
    out="${out%\\n}"
    echo -e "${out}" >| "${__}/matrix.${name}"
}

function Matrix.read() {
  # xstCheck.Matrix "$1" || return 1
 #   return

    while read -r p; do
        printf '%s\n' "${p}"
    done <"${__}/matrix.$1"
}

function Matrix.show() {
    # GOOD
    while IFS=, read -r p; do
        printf '[ %s ]\n' "${p}"
    done <"${__}/matrix.$1"
}

function Matrix.list() {
    local L
    L=("${__}/matrix".*)

    [[ "${#L[@]}" -eq 0 ]] && \
        printf '%s\n' "There are no matrices defined." && \
        return

    for I in "${__}/matrix".*; do
        printf '%s\n' "${I[@]/${__}\/matrix\./}"
    done
}

function Matrix.reset() {
    read -p "Delete all matrices? [y/n]" -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]
    then
        return 1
    fi

    local dir
    dir=$(pwd)

    cd "${__:?}" || return 1

    for I in "./matrix".*; do
        \rm "${I}"
    done

    cd "${dir}" || return 1
}


function Matrix.delete() {
    local dir
    dir=$(pwd)

    cd "${__:?}" || return 1
    :
    if [[ -f "./matrix.${1}" ]]; then
        rm "./matrix.${1}"
        printf 'Matrix %s removed from cache.\n' "${1}"
    else
        printf 'Matrix %s not found.\n' "${1}"
    fi

    cd "${dir}" || return 1

}

function Matrix.clear() {
    local dir
    dir=$(pwd)

    cd "${__:?}" || return 1
    :
    if [[ -f "./matrix.${1}" ]]; then
        printf 'null' >| "./matrix.${1}"
    fi

    cd "${dir}" || return 1
}


###### BOOLEAN OPERATIONS
function Matrix.equiv() {
    local A; A="$(Matrix.read "${1}")"
    local B; B="$(Matrix.read "${2}")"

    if [[ "${A}" == "${B}" ]]
    then
        printf 'TRUE\n' && return 0
    else
        printf 'FALSE\n'
        return 1
    fi
}


###### ARITHMETIC OPERATIONS
function Matrix.add() {
    args=("${@}")

    [[ "${#args[@]}" -lt 2 ]] && \
        printf '%s\n' "Requires at least two args." && \
        return 1

    local A; A="$(Matrix.read "${1}")"
    local B; B="$(Matrix.read "${2}")"

    local count_r; count_r=0
    local count_c; count_c=0
    local result; result=""

    IFS=$'\n'
    for A_r in ${A}; do
        IFS=$'\n'
        B_r=(${B})
        IFS=,
        B_el=(${B_r[$count_r]})
        for A_el in ${A_r}; do
            a="${A_el}"
            b=${B_el[$count_c]}
            result+="$(( a+b )),"
            (( count_c+=1 ))
        done
        result=${result%,}
        #
        result+="\\n"
        count_c=0
        (( count_r+=1 ))
    done
    result="${result%\\n}"
    IFS=
    echo -e "${result}"
}


function Matrix.subtract() {
    local A; A="${1}"
    local B; B="$(Matrix.read "${2}")"

    IFS=
    B='-'${B//$'\n'/$'\n'\-}

    echo -e "${B//,/,-}" >| "${__:?}/matrix.not.${2}"

    Matrix.add "${1}" "not.${2}"
}




##### Transformations
function Matrix.xpose.1() {
    # naive
    local A; A="$(Matrix.read "${1}")"

    IFS=$'\n'

    local count_r; count_r=0
    local count_c; count_c=0
    local result; result=""

    local r; r=''

    IFS=$'\n'
    for A_r in ${A}; do
        IFS=,
        _r=(${A_r[@]})
        IFS=
        r+="${_r[0]},"
 #        IFS=$'\n'
#         IFS=,
#         for A_el in ${A_r}; do
#             a="${A_el}"
#             echo $a;return
#             result+="$(( a )),"
#             (( count_c+=1 ))
#         done
#         result=${result%,}
#         #
#         result+="\\n"
#         count_c=0
#         (( count_r+=1 ))

    done
    echo $r;return
    result="${result%\\n}"
    IFS=
    echo -e "${result}"

}


function Matrix.inverse() {
    :
}
